name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  public:
  label: Build and Test
  discussion: ubuntu-20.04
  status:
    matrix:
     node-version: [21]
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.x'
      - name: Install dependencies and test API service
        run: |
          cd api-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Install dependencies and test Auth service
        run: |
          cd auth-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Build Docker images
        run: |
          docker-compose build
      - name: Run services
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
        # Add integration tests if necessary push_to_registry:
      - name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: demy06031978/microservice-architecture 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

