name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: 'docker:19.03.12'
        options: '--privileged'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies and test API service
        run: |
          cd api-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Install dependencies and test Auth service
        run: |
          cd auth-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Build Docker images
        run: |
          docker-compose build
      - name: Run services
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
        # Add integration tests if necessary
    
  jobs:
        runs-on: ubuntu-latest  # runner name : (ubuntu latest version) 
        steps:
        - uses: actions/checkout@v2 # first action : checkout source code
        
        - name: docker login
          run: | # log into docker hub account
           docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        - name: Get current date # get the date of the build
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
        - name: Build the Docker image # push The image to the docker hub
          run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPO_NAME:${{ steps.date.outputs.date }}
        - name: Docker Push
          run: docker push $DOCKERHUB_USERNAM/$REPO_NAME:${{ steps.date.outputs.date }}
