name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: 'docker:19.03.12'
        options: '--privileged'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies and test API service
        run: |
          cd api-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Install dependencies and test Auth service
        run: |
          cd auth-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Build Docker images
        run: |
          docker-compose build
      - name: Run services
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
        # Add integration tests if necessary
   
      - name: Checkout
        uses: actions/checkout@v4
        with:
           ref: ${{ github.event.inputs.branch }}
           path: ${{ github.sha }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
              
                 push: true
                 tags: demy06031978/microservice-architecture:latest
