name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: 'docker:19.03.12'
        options: '--privileged'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies and test API service
        run: |
          cd api-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Install dependencies and test Auth service
        run: |
          cd auth-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover tests
      - name: Build Docker images
        run: |
          docker-compose build
      - name: Run services
        run: |
          docker-compose up -d
      - name: Run tests
        run: |
        # Add integration tests if necessary 
        
  jobs:
        
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBREPO_TOKEN }}
  

